name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.17
        uses: actions/setup-go@0caeaed6fd66a828038c2da3c0f662a42862658f # v1.1.3
        with:
          go-version: 1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1

      - name: Run checks
        run: |
          make ci
